# Generated by Django 4.2.4 on 2023-11-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_source_context_source_url_alter_source_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="header",
            new_name="title",
        ),
        migrations.AddField(
            model_name="data",
            name="url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
