# Generated by Django 4.2.4 on 2023-11-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_header_data_title_data_url_source_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources_ik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=50)),
                ("data_new", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("day", models.CharField(max_length=50)),
                ("region_code", models.IntegerField()),
                ("region_source", models.CharField(max_length=50)),
                ("domain", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=256)),
                ("category", models.CharField(max_length=50)),
                ("item_title_original", models.CharField(max_length=50)),
                ("item_title_ru", models.CharField(max_length=50)),
                ("article_title_original", models.CharField(max_length=50)),
                ("filter", models.IntegerField()),
            ],
        ),
    ]
