# Generated by Django 4.2.4 on 2023-11-24 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_resources_ik"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resources_ik",
            new_name="Resources",
        ),
    ]
